import turtle 
import time

sample = turtle.Screen().bgcolor("green")

t = turtle.Turtle()
t.speed(10)
t.color("red")
for i in range(0, 36):
    t.left(45)
    t.forward(30)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(135)
    t.right(85)
    t.forward(135)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(20)
    t.right(20)
    t.forward(30)
    t.left(50)
time.sleep(5)


wn = turtle.Screen()
wn.setup(width=400, height=400)
red = turtle.Turtle()

def curve():
    for i in range(200):
        red.right(1)
        red.forward(1)

def heart():
    red.fillcolor('red')
    red.begin_fill()
    red.left(140)
    red.forward(113)
    curve()
    red.left(120)
    curve()
    red.forward(112)
    red.end_fill()

heart()
red.ht()
turtle.done()